#! /bin/sh
# Main config
# {{{
bg=$(xrdb $HOME/.config/X11/xresources -query all | grep background | awk '{print $2}')
fg=$(xrdb $HOME/.config/X11/xresources -query all | grep foreground | awk '{print $2}')
bspc config focused_border_color     "$fg"
bspc config normal_border_color   "$bg"
bspc config border_width 5
bspc config window_gap 15
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
## Pointer actions
bspc config click_to_focus button1
bspc config pointer_action1 move
bspc config top_padding 35

# Monitors
# {{{
bspc monitor -d Terminal Editor Web Extra
# }}}


# Rules
# {{{
# Making all windows floating
bspc rule -a \* state=floating center=true rectangle=955x535+0+0 follow=on
bspc rule -a \*:\* state=floating
bspc rule -a kitty desktop='^1' state=floating

# Rooting windows
bspc rule -a kitty desktop='^1'
bspc rule -a urxvt desktop='^1'

bspc rule -a code-oss desktop='^2'

bspc rule -a Google-chrome desktop='^3' rectangle=1700x870+0+0 center=true
bspc rule -a Firefox desktop='^3' rectangle=1700x870+0+0 center=true
bspc rule -a TelegramDesktop desktop='^3'

bspc rule -a draw.io desktop='^4'
bspc rule -a Thunar desktop='^4'
bspc rule -a Nautilus desktop='^4'

# External rules
bspc config external_rules_command $HOME/.config/bspwm/external.sh

# }}}

# Autostart
# {{{
## Custom scripts
### Autostart script
$HOME/.config/bspwm/autostart.sh &
### Automatic theme changer
$HOME/.config/bspwm/theme_changer.sh &
### Automatic sleep every 30 minutes
killall -q sleep30.sh; $HOME/.config/bspwm/sleep30.sh &
### Polybar
$HOME/.config/polybar/launch.sh
# }}}
