#!/usr/bin/env bash
function getColor() {
	echo "$(xrdb -query | grep $1 | awk '{print $2}')"
}

bg=$(getColor *.background:)
fg=$(getColor *.foreground:)
color1=$(getColor *.color1:)
color2=$(getColor *.color2:)
color3=$(getColor *.color3:)
color4=$(getColor *.color4:)
color5=$(getColor *.color5:)
color6=$(getColor *.color6:)
color7=$(getColor *.color7:)
color8=$(getColor *.color8:)
color9=$(getColor *.color9:)
color10=$(getColor *.color10:)
color11=$(getColor *.color11:)
color12=$(getColor *.color12:)
color13=$(getColor *.color13:)
color14=$(getColor *.color14:)
color15=$(getColor *.color15:)

zathurarc=$(cat <<FILE
set font "Lato 12"

set completion-bg "$bg"
set completion-fg "$fg"
set completion-group-bg "$bg"
set completion-group-fg "$color2"
set completion-highlight-bg "$fg"
set completion-highlight-fg "$bg"
set default-bg "$bg"
set default-fg "$fg"
set inputbar-bg "$bg"
set inputbar-fg "$fg"
set notification-bg "$bg"
set notification-fg "$fg"
set notification-error-bg "$color1"
set notification-error-fg "$fg"
set notification-warning-bg "$color1"
set notification-warning-fg "$fg"
set statusbar-bg "$bg"
set statusbar-fg "$fg"
set index-bg "$bg"
set index-fg "$fg"
set index-active-bg "$fg"
set index-active-fg "$bg"
set render-loading-bg "$bg"
set render-loading-fg "$fg"

set smooth-scroll true
set window-title-home-tilde true
set statusbar-basename true
set selection-clipboard clipboard

set adjust-open "width"
set zoom-center "true"
set pages-per-row 1
set scroll-page-aware "true"
set scroll-step 100
set scroll-full-overlap 0.01
set smooth-scroll "true"
FILE
)

printf "$zathurarc\n" > $HOME/.config/zathura/zathurarc
